FROM ubuntu:bionic

RUN apt-get update \
  && apt-get install -y \
  bind9 \
  bind9utils \
  bind9-doc

# Enable IPv4
RUN sed -i 's/OPTIONS=.*/OPTIONS="-4 -u bind"/' /etc/default/bind9

# Copy configuration files
COPY named.conf /etc/bind/
COPY wtL2-8.ephec-ti.be /etc/bind/


# Run eternal loop
CMD ["/bin/bash", "-c", "while :; do sleep 10; done"]"-c" , "while:; do sleep 10; done" ]